name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download spaCy model
      run: python -m spacy download en_core_web_sm
    
    - name: Build with PyInstaller
      run: pyinstaller --clean --onefile app.spec
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: SRT-Generator-Windows
        path: dist/SRT Generator.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download spaCy model
      run: python -m spacy download en_core_web_sm
    
    - name: Build with PyInstaller
      run: pyinstaller --clean --onefile app.spec
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: SRT-Generator-macOS
        path: dist/SRT Generator

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Download spaCy model
      run: python -m spacy download en_core_web_sm
    
    - name: Build with PyInstaller
      run: pyinstaller --clean --onefile app.spec
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: SRT-Generator-Linux
        path: dist/SRT Generator
